kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devops
nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080   
      - containerPort: 30090
        hostPort: 30090     
        protocol: TCP
  - role: worker
    image: kindest/node:v1.34.0