apiVersion: v1
kind: Service
metadata:
  name: luhn-api-service
spec:
  selector:
    app: luhn-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080 
  type: NodePort
